In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/cleaned/social_media_scored.csv")

df.head()

,age,gender,job_type,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,...,screen_time_before_sleep,breaks_during_work,uses_focus_apps,has_digital_wellbeing_enabled,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score,productivity_score,productivity_level
0,56,Male,Unemployed,4.180940,Facebook,61,6.753558,8.040464,7.291555,4.0,...,0.419102,8,False,False,4,11,21.927072,6.336688,53.323774,Moderate Productivity
1,46,Male,Health,3.249603,Twitter,59,9.169296,5.063368,5.165093,7.0,...,0.671519,7,True,True,2,25,0.000000,3.412427,60.457574,Moderate Productivity
2,32,Male,Finance,NaN,Twitter,57,7.910952,3.861762,3.474053,4.0,...,0.624378,0,True,False,3,17,10.322044,2.474944,NaN,Low Productivity
3,60,Female,Unemployed,NaN,Facebook,59,6.355027,2.916331,1.774869,6.0,...,1.204540,1,False,False,0,4,23.876616,1.733670,NaN,Low Productivity
4,38,Male,Finance,1.512568,Twitter,50,6.429312,NaN,4.081026,5.0,...,1.518612,5,False,True,5,2,0.000000,4.568728,59.066630,Moderate Productivity

In [3]:
def generate_recommendations(row):
    
    recommendations = []
    
    if row["daily_social_media_time"] > 4:
        recommendations.append("Reduce daily social media usage")
        
    if row["sleep_hours"] < 6:
        recommendations.append("Increase sleep hours for better focus")
        
    if row["stress_level"] > 7:
        recommendations.append("Manage stress using relaxation techniques")
        
    if row["screen_time_before_sleep"] > 2:
        recommendations.append("Avoid screen time before sleep")
        
    if row["breaks_during_work"] < 2:
        recommendations.append("Take short breaks during work for productivity")
        
    if row["uses_focus_apps"] == False:
        recommendations.append("Consider using focus apps to avoid distractions")
        
    return recommendations

In [4]:
df["recommendations"] = df.apply(generate_recommendations, axis=1)

In [5]:
df[[
    "productivity_score",
    "productivity_level",
    "recommendations"
]].head()

,productivity_score,productivity_level,recommendations
0,53.323774,Moderate Productivity,"[Reduce daily social media usage, Increase sle..."
1,60.457574,Moderate Productivity,[Increase sleep hours for better focus]
2,NaN,Low Productivity,[Take short breaks during work for productivity]
3,NaN,Low Productivity,[Take short breaks during work for productivit...
4,59.066630,Moderate Productivity,"[Increase sleep hours for better focus, Consid..."

In [6]:
df["productivity_score"] = df["productivity_score"].fillna(df["productivity_score"].mean())

In [7]:
df["productivity_score"].isnull().sum()

np.int64(0)

In [10]:
df.to_csv("../data/cleaned/social_media_final.csv", index=False)

In [9]:
df[["productivity_level","recommendations"]].head()

      productivity_level                                    recommendations
0  Moderate Productivity  [Reduce daily social media usage, Increase sle...
1  Moderate Productivity            [Increase sleep hours for better focus]
2       Low Productivity   [Take short breaks during work for productivity]
3       Low Productivity  [Take short breaks during work for productivit...
4  Moderate Productivity  [Increase sleep hours for better focus, Consid...